# Generated by Django 5.0.1 on 2024-03-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='books',
            name='password',
        ),
        migrations.AddField(
            model_name='books',
            name='botao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='ligaRobo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='resetContador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='valorContagem',
            field=models.IntegerField(default=0),
        ),
    ]
